// Parameter descriptions and metadata for the info modal

import type { ColorScaleType } from "../../utils/colorScales";

export interface ParameterDescription {
  shortDescription: string;
  aboutDescription: string;
  technicalDescription: string;
  formula: string;
  unit: string;
  legendMin: number;
  legendMax: number;
  colorScaleType: ColorScaleType;
}

export const PARAMETER_DESCRIPTIONS: Record<string, ParameterDescription> = {
  annual_precipitation: {
    shortDescription: "The total amount of rainfall accumulated over the year across Ghana.",
    aboutDescription: "Annual precipitation is one of the clearest indicators of water availability across Ghana. It shapes river flows, reservoir recharge, rain-fed agriculture, flood risk, and groundwater replenishment from the coast to the northern savanna.",
    technicalDescription: "Sum of daily precipitation totals across the full annual period.",
    formula: "Sum(P)",
    unit: "mm",
    legendMin: 700,
    legendMax: 1800,
    colorScaleType: "precipitation",
  },
  wet_season_precipitation: {
    shortDescription: "The total amount of rainfall accumulated during Ghana's main rainy periods, including the southern major season from February to August and the later southern season from September to November.",
    aboutDescription: "Wet season precipitation is especially important for farming calendars, flood preparedness, and water resource planning in Ghana. In southern Ghana, the longer major season runs from February through August, followed by a later season from September through November. Changes in these rainfall totals can strongly affect crop establishment, road access, and seasonal storage in rivers and reservoirs.",
    technicalDescription: "Sum of daily precipitation totals during the defined rainy-season periods used in the atlas, including the southern major season (Feb-Aug) and later southern season (Sep-Nov).",
    formula: "Sum(P, Feb-Nov rainy periods)",
    unit: "mm",
    legendMin: 400,
    legendMax: 1400,
    colorScaleType: "precipitation",
  },
  heavy_precip_10mm: {
    shortDescription: "The number of days per year when rainfall exceeds 10 mm. This indicator helps track the frequency of moderate to heavy rainfall events across Ghana.",
    aboutDescription: "In Ghana, where rain-fed agriculture dominates, tracking days with over 10 mm of rainfall is essential. This metric helps farmers across the cocoa belt, the Guinea savanna, and coastal plains plan planting schedules and anticipate waterlogging risks that can damage crops and rural roads.",
    technicalDescription: "Annual count of days where daily precipitation total is greater than or equal to 10 mm.",
    formula: "Count(P >= 10 mm)",
    unit: "days",
    legendMin: 0,
    legendMax: 100,
    colorScaleType: "precipitation",
  },
  heavy_precip_20mm: {
    shortDescription: "The number of days per year when rainfall exceeds 20 mm. This tracks very heavy rainfall events that can cause flooding in Ghana.",
    aboutDescription: "Days exceeding 20 mm of rainfall represent significant downpour events in Ghana. These heavy rains frequently trigger urban flooding in cities like Accra, Kumasi, and Tamale, overwhelm drainage systems, and can cause erosion on deforested hillsides in the Volta and Eastern regions.",
    technicalDescription: "Annual count of days where daily precipitation total is greater than or equal to 20 mm.",
    formula: "Count(P >= 20 mm)",
    unit: "days",
    legendMin: 0,
    legendMax: 60,
    colorScaleType: "precipitation",
  },
  wet_days: {
    shortDescription: "The total number of days per year with measurable precipitation (at least 1 mm of rainfall) across Ghana.",
    aboutDescription: "Ghana experiences distinct wet and dry seasons that vary by region. The south-west receives rain for most of the year with two rainy seasons, while the northern savanna has a single rainy season. Tracking wet days helps understand shifts in these seasonal patterns that are critical for food security and water supply.",
    technicalDescription: "Annual count of days where daily precipitation total is greater than or equal to 1 mm.",
    formula: "Count(P >= 1 mm)",
    unit: "days",
    legendMin: 0,
    legendMax: 200,
    colorScaleType: "precipitation",
  },
  dry_days: {
    shortDescription: "The total number of days per year with no significant precipitation (less than 1 mm of rainfall) in Ghana.",
    aboutDescription: "Dry days are a critical concern in Ghana, particularly in the northern regions where the Harmattan season brings extended periods without rain. Prolonged dry spells threaten smallholder farming, reduce water levels in the Volta Lake reservoir, and increase bushfire risk in the savanna zones.",
    technicalDescription: "Annual count of days where daily precipitation total is less than 1 mm.",
    formula: "Count(P < 1 mm)",
    unit: "days",
    legendMin: 0,
    legendMax: 365,
    colorScaleType: "dry_days",
  },
  max_1day_precip: {
    shortDescription: "The highest amount of rainfall recorded in a single day during the year. Indicates extreme rainfall intensity in Ghana.",
    aboutDescription: "Ghana is increasingly vulnerable to extreme single-day rainfall events. In Accra and other low-lying coastal cities, a single intense downpour can overwhelm drainage infrastructure and cause severe flash flooding. This indicator is vital for disaster preparedness and urban planning across Ghana's rapidly growing cities.",
    technicalDescription: "Maximum daily precipitation total recorded in a single day during the annual period.",
    formula: "max(P1)",
    unit: "mm",
    legendMin: 0,
    legendMax: 200,
    colorScaleType: "precipitation",
  },
  max_3day_precip: {
    shortDescription: "The highest cumulative rainfall over any 3-day period during the year. Indicates sustained heavy rainfall events in Ghana.",
    aboutDescription: "In regions where intense rain persists for multiple days in a row, the Max 3-Day Precipitation captures multi-day storm events common during Ghana's peak rainy seasons. Sustained heavy rainfall in the Volta Basin and along the south-western coast can cause river flooding, damage to cocoa farms, and landslides in hilly terrain.",
    technicalDescription: "Maximum cumulative precipitation total over any consecutive 3-day period during the annual period.",
    formula: "max(P1 + P2 + P3)",
    unit: "mm",
    legendMin: 0,
    legendMax: 300,
    colorScaleType: "precipitation",
  },
  max_5day_precip: {
    shortDescription: "The highest cumulative rainfall over any 5-day period during the year. Tracks extended storm systems affecting Ghana.",
    aboutDescription: "Extended wet spells lasting five or more days can saturate soils across Ghana, leading to widespread flooding in the White Volta and Oti river basins. These prolonged events are particularly damaging in the Upper East and Upper West regions, where they can wash away crops, displace communities, and cut off rural roads.",
    technicalDescription: "Maximum cumulative precipitation total over any consecutive 5-day period during the annual period.",
    formula: "max(sum(Pi, i=1..5))",
    unit: "mm",
    legendMin: 0,
    legendMax: 400,
    colorScaleType: "precipitation",
  },

  maize_heat_units: {
    shortDescription: "A crop-specific heat accumulation measure for maize growth, accounting for both day and night temperatures in Ghana.",
    aboutDescription: "Maize is a staple crop across Ghana, grown from the coastal plains to the northern savanna. For maize-focused analysis, Maize Heat Units are often more agronomically meaningful than generic Growing Degree Days because they better reflect how maize responds to warm tropical conditions.",
    technicalDescription: "Calculated using the Ontario Maize Heat Unit formula, which combines daytime maximum temperature contribution and nighttime minimum temperature contribution with specific thresholds for maize growth.",
    formula: "MHU = sum((Ymax + Ymin) / 2)",
    unit: "MHU",
    legendMin: 1000,
    legendMax: 4000,
    colorScaleType: "temperature",
  },
  gdd_base_5: {
    shortDescription: "Growing Degree Days above 5C provide a low-threshold thermal sum. In Ghana this is mainly a comparison metric, not the usual operational crop standard.",
    aboutDescription: "Because Ghana is warm year-round, a 5C base captures almost all thermal accumulation. That makes it useful for broad comparison, but less practical for operational crop planning than base 10C or crop-specific measures such as Maize Heat Units.",
    technicalDescription: "Annual sum of degrees Celsius that each day's mean temperature exceeds 5C. Values below the base temperature contribute zero.",
    formula: "GDD = sum(max(Tmean - 5, 0))",
    unit: "Degree Days",
    legendMin: 0,
    legendMax: 5000,
    colorScaleType: "temperature",
  },
  gdd_base_10: {
    shortDescription: "Growing Degree Days above 10C are the main warm-season thermal sum and the closest general-purpose GDD standard for Ghanaian crop analysis.",
    aboutDescription: "For warm-season crop analysis in Ghana, the 10C base is the most practical general-purpose benchmark. It is broadly aligned with crops such as maize and rice and works well as a standard thermal accumulation indicator when you are not using a crop-specific system like Maize Heat Units.",
    technicalDescription: "Annual sum of degrees Celsius that each day's mean temperature exceeds 10C. This is the preferred general-purpose GDD threshold in this atlas.",
    formula: "GDD = sum(max(Tmean - 10, 0))",
    unit: "Degree Days",
    legendMin: 0,
    legendMax: 4000,
    colorScaleType: "temperature",
  },
  gdd_base_15: {
    shortDescription: "Growing Degree Days above 15C focus on higher-threshold heat accumulation for more heat-demanding tropical crop conditions.",
    aboutDescription: "A 15C base is better treated as a specialized indicator for hotter crop thresholds rather than a national default. It can be useful when comparing thermal suitability for more heat-demanding tropical crops, but it is not the broad standard benchmark for Ghana.",
    technicalDescription: "Annual sum of degrees Celsius that each day's mean temperature exceeds 15C. Higher base temperatures emphasize heat-demanding crop conditions.",
    formula: "GDD = sum(max(Tmean - 15, 0))",
    unit: "Degree Days",
    legendMin: 0,
    legendMax: 3000,
    colorScaleType: "temperature",
  },
  gdd_base_4: {
    shortDescription: "Growing Degree Days above 4C capture almost all heat accumulation in Ghana, so they are best used for comparison rather than routine crop decision-making.",
    aboutDescription: "In Ghana's tropical climate, a 4C base is so low that it functions mainly as a broad thermal-resource indicator. It can help with cross-region or cross-country comparison, but it is not the standard operational threshold for Ghanaian crop planning.",
    technicalDescription: "Annual sum of degrees Celsius that each day's mean temperature exceeds 4C. This is a low-threshold comparison metric.",
    formula: "GDD = sum(max(Tmean - 4, 0))",
    unit: "Degree Days",
    legendMin: 0,
    legendMax: 6000,
    colorScaleType: "temperature",
  },

  very_hot_days_35: {
    shortDescription: "The number of days per year when the maximum temperature exceeds 35C. This is the backend-supported extreme heat indicator currently available in the atlas.",
    aboutDescription: "Days above 35C represent dangerous heat conditions in many parts of Ghana, especially across the northern savanna and dense urban areas with limited cooling. Tracking these very hot days helps identify where climate change is pushing conditions into more hazardous territory for health, labour, and agriculture.",
    technicalDescription: "Annual count of days where daily maximum temperature is greater than or equal to 35C.",
    formula: "Count(Tmax >= 35C)",
    unit: "days",
    legendMin: 0,
    legendMax: 200,
    colorScaleType: "hot_days",
  },
  very_hot_days_30: {
    shortDescription: "The number of days per year when the maximum temperature exceeds 30C. A key indicator of heat stress in Ghana.",
    aboutDescription: "In Ghana's tropical climate, days above 30C are common but their increasing frequency is a concern. Northern regions like Tamale and Bolgatanga already experience extreme heat for much of the year. Rising very hot days threaten outdoor workers, reduce labour productivity, and strain health services across the country.",
    technicalDescription: "Annual count of days where daily maximum temperature is greater than or equal to 30C.",
    formula: "Count(Tmax >= 30C)",
    unit: "days",
    legendMin: 0,
    legendMax: 200,
    colorScaleType: "hot_days",
  },
  warmest_max_temp: {
    shortDescription: "The highest maximum temperature recorded during the year. Indicates peak heat intensity in Ghana.",
    aboutDescription: "Ghana's warmest temperatures are typically recorded in the northern savanna during the dry season (February-April), when temperatures can exceed 40C. This indicator is critical for heat emergency planning in cities like Tamale and Wa, and for understanding how climate change is pushing peak temperatures to new extremes.",
    technicalDescription: "The highest daily maximum temperature recorded during the annual period.",
    formula: "max(Tmax)",
    unit: "C",
    legendMin: 25,
    legendMax: 50,
    colorScaleType: "hot_days",
  },
  heat_wave_count: {
    shortDescription: "The number of distinct heat wave events per year. Heat waves are a growing concern across Ghana.",
    aboutDescription: "Heat waves in Ghana can be devastating, particularly in the Upper East, Upper West, and Northern regions where access to cooling is limited. Multiple heat wave events in a year compound health risks for vulnerable populations, reduce crop yields, and increase water demand during already-stressed dry seasons.",
    technicalDescription: "Count of distinct heat wave events, where a heat wave is defined as 3 or more consecutive days with maximum temperature exceeding 32C.",
    formula: "N(events where Tmax >= 32C for >= 3 consecutive days)",
    unit: "events",
    legendMin: 0,
    legendMax: 20,
    colorScaleType: "hot_days",
  },
  heat_wave_avg_length: {
    shortDescription: "The average duration of heat wave events in days. Longer heat waves have more severe impacts on Ghanaian communities.",
    aboutDescription: "Extended heat waves are particularly dangerous in Ghana, where many homes lack air conditioning and outdoor labour in farming, construction, and mining is widespread. Longer heat waves strain water supplies, increase the risk of heat-related illness, and can cause significant losses in livestock and poultry production.",
    technicalDescription: "Mean duration (in days) of heat wave events during the annual period, where a heat wave is 3+ consecutive days above 32C.",
    formula: "sum(heat wave days) / N(heat waves)",
    unit: "days",
    legendMin: 0,
    legendMax: 15,
    colorScaleType: "hot_days",
  },
  longest_hot_spell: {
    shortDescription: "The longest consecutive sequence of days with maximum temperature above 30C during the year in Ghana.",
    aboutDescription: "Ghana's northern regions can experience continuous stretches of extreme heat lasting weeks during the dry season. The longest hot spell indicator reveals how sustained these heat events are, which is critical for planning water rationing, protecting livestock, and supporting communities through extended periods without relief.",
    technicalDescription: "Maximum number of consecutive days during the annual period where daily maximum temperature exceeds 30C.",
    formula: "max(consecutive days where Tmax >= 30C)",
    unit: "days",
    legendMin: 0,
    legendMax: 100,
    colorScaleType: "hot_days",
  },
  hot_season: {
    shortDescription: "The length of the hot season in Ghana, when daily maximum temperatures regularly exceed 30C.",
    aboutDescription: "Ghana's hot season varies by region: the north experiences a pronounced hot dry season from February to April, while the south has more moderate temperatures year-round due to coastal influence. A lengthening hot season affects energy demand, water availability from the Volta reservoir, and the viability of outdoor economic activities.",
    technicalDescription: "Duration of the annual period between the first and last occurrence of daily maximum temperature exceeding 30C.",
    formula: "Last(Tmax >= 30C) - First(Tmax >= 30C)",
    unit: "days",
    legendMin: 0,
    legendMax: 250,
    colorScaleType: "hot_days",
  },
  extreme_hot_32: {
    shortDescription: "The number of days per year when the maximum temperature exceeds 32C in Ghana. Indicates severe heat conditions.",
    aboutDescription: "At 32C and above, outdoor work becomes dangerous without precautions. In Ghana, where agriculture, construction, and artisanal mining employ millions of outdoor workers, tracking extremely hot days is essential for occupational health planning and for designing climate adaptation strategies in vulnerable districts.",
    technicalDescription: "Annual count of days where daily maximum temperature is greater than or equal to 32C.",
    formula: "Count(Tmax >= 32C)",
    unit: "days",
    legendMin: 0,
    legendMax: 150,
    colorScaleType: "hot_days",
  },
  extreme_hot_34: {
    shortDescription: "The number of days per year when the maximum temperature exceeds 34C in Ghana. Indicates extreme heat conditions.",
    aboutDescription: "Days exceeding 34C represent the most dangerous heat conditions in Ghana. These temperatures, most frequent in the Upper East and Northern regions, pose serious risks of heat stroke, are lethal for poultry and livestock, and can cause significant yield losses in crops like maize, millet, and sorghum.",
    technicalDescription: "Annual count of days where daily maximum temperature is greater than or equal to 34C.",
    formula: "Count(Tmax >= 34C)",
    unit: "days",
    legendMin: 0,
    legendMax: 100,
    colorScaleType: "hot_days",
  },

  mean_temp: {
    shortDescription: "The average of daily mean temperatures across the year. A fundamental climate indicator for Ghana.",
    aboutDescription: "Ghana's mean temperature varies from about 26C along the coast to over 28C in the northern savanna. Rising mean temperatures are a clear signal of climate change, affecting cocoa suitability zones, increasing evaporation from the Volta Lake, and intensifying heat stress for communities across all regions.",
    technicalDescription: "Annual average of daily mean temperatures, where daily mean is the average of daily maximum and minimum temperatures.",
    formula: "Tmean = (Tmax + Tmin) / 2",
    unit: "C",
    legendMin: 20,
    legendMax: 35,
    colorScaleType: "temperature",
  },
  max_temp: {
    shortDescription: "The average of daily maximum temperatures across the year. Indicates typical daytime heat in Ghana.",
    aboutDescription: "Daytime temperatures in Ghana shape daily life, from when outdoor markets operate to agricultural work schedules. The northern regions consistently record higher maximum temperatures than the coast. Understanding how daytime heat is changing helps plan for energy demand, urban heat islands in Accra and Kumasi, and worker safety.",
    technicalDescription: "Annual average of daily maximum temperatures.",
    formula: "Annual mean of daily Tmax",
    unit: "C",
    legendMin: 25,
    legendMax: 40,
    colorScaleType: "temperature",
  },
  min_temp: {
    shortDescription: "The average of daily minimum temperatures across the year. Indicates typical nighttime conditions in Ghana.",
    aboutDescription: "Nighttime temperatures in Ghana determine comfort during sleep and affect crop respiration rates. Warmer nights mean less relief from daytime heat, increased energy use for cooling, and reduced yields for temperature-sensitive crops like cocoa. Coastal cities experience less nighttime cooling due to humidity and urban heat effects.",
    technicalDescription: "Annual average of daily minimum temperatures.",
    formula: "Annual mean of daily Tmin",
    unit: "C",
    legendMin: 15,
    legendMax: 30,
    colorScaleType: "temperature",
  },

  coldest_min_temp: {
    shortDescription: "The lowest minimum temperature recorded during the year. Indicates the coolest conditions in Ghana.",
    aboutDescription: "While Ghana does not experience freezing temperatures, the coldest nights occur during the Harmattan season (December-February) when dry, dusty winds from the Sahara bring cooler conditions, particularly in the northern regions and highland areas around the Kwahu Plateau and Akuapem Ridge.",
    technicalDescription: "The lowest daily minimum temperature recorded during the annual period.",
    formula: "min(Tmin)",
    unit: "C",
    legendMin: 10,
    legendMax: 25,
    colorScaleType: "temperature",
  },
};

export const getParameterDescription = (parameterId: string): ParameterDescription => {
  return (
    PARAMETER_DESCRIPTIONS[parameterId] || {
      shortDescription: "Climate parameter data for analysis across Ghana's 261 districts.",
      aboutDescription: "This climate variable provides insights into Ghana's regional climate patterns and how they are projected to change over time across the country's diverse ecological zones.",
      technicalDescription: "Computed from climate model outputs.",
      formula: "",
      unit: "",
      legendMin: 0,
      legendMax: 100,
      colorScaleType: "temperature",
    }
  );
};
