// Generated by ghclimateatlas-backend/scripts/extract_coastline.py - do not edit by hand.
// Districts whose boundary touches the ocean coastline, ordered west to east.
export const COASTAL_DISTRICT_IDS: readonly string[] = [
  "GH-WES-JOMOR", // Jomoro
  "GH-WES-ELLEM", // Ellembelle
  "GH-WES-NZEMA", // Nzema East
  "GH-WES-AHANT", // Ahanta West
  "GH-WES-SEKON", // Sekondi Takoradi
  "GH-WES-SHAMA", // Shama
  "GH-CEN-KOMEN", // Komenda-Edina-Eguafo-Abirem-
  "GH-CEN-CAPE_", // Cape Coast
  "GH-CEN-ABURA", // Abura-Asebu-Kwamankese
  "GH-CEN-MFANT", // Mfantseman
  "GH-CEN-EKUMF", // Ekumfi
  "GH-CEN-GOMOA_3", // Gomoa West
  "GH-CEN-GOMOA", // Gomoa Central
  "GH-CEN-EFFUT", // Effutu
  "GH-CEN-AWUTU", // Awutu Senya East
  "GH-CEN-GOMOA_2", // Gomoa East
  "GH-GRE-WEIJA", // Weija Gbawe
  "GH-GRE-ABLEK_3", // Ablekuma West
  "GH-GRE-ACCRA", // Accra
  "GH-GRE-KORLE", // Korle-Klottey
  "GH-GRE-LA_DA", // La-Dade-Kotopon
  "GH-GRE-LEDZO", // Ledzokuku
  "GH-GRE-KROWO", // Krowor
  "GH-GRE-TEMA_", // Tema West
  "GH-GRE-TEMA", // Tema
  "GH-GRE-KPONE", // Kpone-Katamanso
  "GH-GRE-NINGO", // Ningo-Prampram
  "GH-GRE-ADA_W", // Ada West
  "GH-GRE-ADA_E", // Ada East
  "GH-VOL-ANLOG", // Anloga
  "GH-VOL-KETA_", // Keta Municipal
  "GH-VOL-KETU__2", // Ketu South
];
